#!/bin/bash

if [ -z "$1" ]
  then
    echo "Usage: ./new-update {destination_tag} {slug-name-of-update}"
    echo "Options: --draft"
    exit 1
fi

DATE=`date +%Y-%m-%d`

if [ "$3" == "--draft" ]; then
    FILE="_drafts/$2.html"
    DRAFT=true
else
    FILE="_posts/$DATE-$2.html"
    DRAFT=false
fi

touch $FILE

echo "---" >> $FILE
echo "title:  " >> $FILE
if [ "$DRAFT" = false ]; then
  echo "date: $DATE" >> $FILE
fi
echo "category: updates" >> $FILE
echo "layout: update" >> $FILE
echo "banner: " >> $FILE
echo "override_home_banner: false" >> $FILE
echo "tags:" >> $FILE
echo "  - $1" >> $FILE
echo "---" >> $FILE

vim $FILE