#!/bin/bash

if [ -z "$1" ]
  then
    echo "Usage: ./new-destination {slug-name-of-destination}"
    exit 1
fi

DATE=`date +%Y-%m-%d`
FILE="_posts/$DATE-$1.html"

touch $FILE

echo "---" >> $FILE
echo "title:  " >> $FILE
echo "date: $DATE" >> $FILE
echo "category: destinations" >> $FILE
echo "layout: destination" >> $FILE
echo "update_tag: " >> $FILE
echo "home_title: " >> $FILE
echo "lat: " >> $FILE
echo "lng: " >> $FILE
echo "miles: " >> $FILE
echo "banner: " >> $FILE
echo "tags:" >> $FILE
echo "  - loop2" >> $FILE
echo "---" >> $FILE

vim $FILE
