#!/bin/bash

if [ -z "$1" ]
  then
    echo "Usage: ./new-article {slug-name-of-article}"
    echo "Options: --draft"
    exit 1
fi

DATE=`date +%Y-%m-%d`

if [ "$2" == "--draft" ]; then
    FILE="_drafts/$1.html"
    DRAFT=true
else
    FILE="_posts/$DATE-$1.html"
    DRAFT=false
fi

touch $FILE

echo "---" >> $FILE
echo "title:  " >> $FILE
if [ "$DRAFT" = false ]; then
  echo "date: $DATE" >> $FILE
fi
echo "category: articles" >> $FILE
echo "layout: article" >> $FILE
echo "banner: " >> $FILE
echo "override_home_banner: false" >> $FILE
echo "---" >> $FILE

vim $FILE