#!/bin/bash

if [ -z "$1" ]
  then
    echo "Usage: ./publish-draft {slug-name-of-draft}"
    exit 1
fi

DATE=`date +%Y-%m-%d`
DRAFTFILE="_drafts/$1.html"
NEWFILE="_posts/$DATE-$1.html"

awk -v n=3 -v s="date: $DATE" 'NR == n {print s} {print}' "$DRAFTFILE" > "$NEWFILE"
rm -f "$DRAFTFILE"